/** Part 05 — 20-section enterprise module map (SRS blueprint) */

export type ErpModuleSection = {
  id: string;
  section: string;
  title: string;
  href: string;
  summary: string;
  features: string[];
  permission: string;
};

export const ERP_SECTIONS: ErpModuleSection[] = [
  {
    id: "overview",
    section: "5.1",
    title: "Operations overview",
    href: "/staff",
    summary: "Command center, billing, CRM, projects, and daily operations.",
    features: ["Command center", "Billing", "CRM", "Projects"],
    permission: "erp.analytics.view",
  },
  {
    id: "organization",
    section: "5.1b",
    title: "Organization & Branches",
    href: "/admin/erp/organization",
    summary: "Companies, branches, departments — multi-tenant ready for SaaS.",
    features: ["Organizations", "Branches", "Departments", "Cost centers"],
    permission: "erp.analytics.view",
  },
  {
    id: "hrm",
    section: "5.2",
    title: "Human Resource Management",
    href: "/admin/erp/hr",
    summary: "Employee master, org hierarchy, leave approvals, holidays, documents, CSV.",
    features: ["Employee DB", "Hierarchy", "Attendance", "Leave", "Documents", "ESS"],
    permission: "erp.hr.view",
  },
  {
    id: "finance",
    section: "5.3",
    title: "Finance & Accounting",
    href: "/admin/erp/finance",
    summary: "GL, AR/AP, cash flow, budgeting, tax, and statements.",
    features: ["Chart of Accounts", "AR/AP", "Cash flow", "Budgets", "Tax", "Statements"],
    permission: "erp.finance.view",
  },
  {
    id: "coa",
    section: "5.3b",
    title: "Chart of Accounts",
    href: "/admin/erp/coa",
    summary: "Ledger account structure for GL, income, and expense tracking.",
    features: ["Assets", "Liabilities", "Equity", "Revenue", "Expenses"],
    permission: "erp.finance.view",
  },
  {
    id: "approvals",
    section: "5.3c",
    title: "Approval Workflows",
    href: "/admin/erp/approvals",
    summary: "Leave, purchase, expense, quotation, and project approvals.",
    features: ["Multi-level", "Notifications", "Audit trail", "Linked records"],
    permission: "erp.analytics.view",
  },
  {
    id: "procurement",
    section: "5.4",
    title: "Procurement",
    href: "/admin/erp/procurement",
    summary: "PRs, POs, vendors, GRN, and supplier payments.",
    features: ["Purchase requests", "POs", "Vendors", "GRN", "Supplier payments"],
    permission: "erp.procurement.view",
  },
  {
    id: "inventory",
    section: "5.5",
    title: "Inventory Management",
    href: "/admin/erp/inventory",
    summary: "Warehouses, stock moves, batches, expiry, and valuation.",
    features: ["Multi-warehouse", "Stock moves", "Batch/expiry", "Adjustments"],
    permission: "erp.inventory.view",
  },
  {
    id: "scm",
    section: "5.6",
    title: "Supply Chain (SCM)",
    href: "/admin/erp/scm",
    summary: "Procurement, warehouse, logistics, and shipment tracking.",
    features: ["Logistics", "Distribution", "Delivery planning", "Shipments"],
    permission: "erp.scm.view",
  },
  {
    id: "manufacturing",
    section: "5.7",
    title: "Manufacturing",
    href: "/admin/erp/manufacturing",
    summary: "BOM, production planning, work orders, and QC.",
    features: ["BOM", "Production orders", "QC", "Costing"],
    permission: "erp.mfg.view",
  },
  {
    id: "eam",
    section: "5.8",
    title: "Enterprise Asset Management",
    href: "/admin/erp/assets",
    summary: "Registration, allocation, maintenance, depreciation, disposal.",
    features: ["Registry", "Maintenance", "Depreciation", "Audit"],
    permission: "erp.assets.view",
  },
  {
    id: "esm",
    section: "5.9",
    title: "Enterprise Service Management",
    href: "/admin/erp/esm",
    summary: "Service catalog, incidents, problems, changes, and SLAs.",
    features: ["Catalog", "Incidents", "Changes", "SLA"],
    permission: "erp.esm.view",
  },
  {
    id: "fsm",
    section: "5.10",
    title: "Field Service Management",
    href: "/admin/erp/fsm",
    summary: "Technicians, scheduling, GPS, signatures, and mobile work orders.",
    features: ["Scheduling", "GPS", "Signatures", "Service reports"],
    permission: "erp.fsm.view",
  },
  {
    id: "projects",
    section: "5.11",
    title: "Project Management",
    href: "/admin/erp/projects",
    summary: "Projects, milestones, tasks, progress boards, budgets, and billing.",
    features: ["Milestones", "Progress board", "Resources", "Project billing"],
    permission: "erp.projects.view",
  },
  {
    id: "csm",
    section: "5.12",
    title: "Customer Service Management",
    href: "/admin/support",
    summary: "Tickets, complaints, SLA, escalation, and CSAT (linked to Part 04).",
    features: ["Tickets", "SLA", "Escalation", "CSAT"],
    permission: "erp.analytics.view",
  },
  {
    id: "iot",
    section: "5.13",
    title: "Industrial IoT",
    href: "/admin/erp/iot",
    summary: "Devices, sensors, machine health, energy, and alerts.",
    features: ["Devices", "Sensors", "Health", "Alerts"],
    permission: "erp.iot.view",
  },
  {
    id: "pdm",
    section: "5.14",
    title: "Predictive Maintenance",
    href: "/admin/erp/maintenance",
    summary: "AI failure hints, calendars, history, and asset health scores.",
    features: ["Health scores", "Schedules", "History", "AI hints"],
    permission: "erp.assets.view",
  },
  {
    id: "ai",
    section: "5.15",
    title: "AI Enterprise Platform",
    href: "/admin/erp/ai",
    summary: "Business assistant, reports, documents, email, and forecasting.",
    features: ["AI assistant", "Reports", "Docs", "Forecasting"],
    permission: "erp.ai.view",
  },
  {
    id: "bi",
    section: "5.16",
    title: "Business Intelligence",
    href: "/admin/erp/performance",
    summary: "KPI, revenue, sales, customer, financial, heat maps, and executive dashboards.",
    features: ["KPI", "Reports", "Heat maps", "Alerts", "Forecasts"],
    permission: "erp.analytics.view",
  },
  {
    id: "dms",
    section: "5.17",
    title: "Document Management",
    href: "/admin/erp/documents",
    summary: "Repository, versions, ACL, OCR search, e-sign, knowledge base, and workflows.",
    features: ["Repository", "Versions", "KB/Wiki", "E-sign", "Audit"],
    permission: "erp.dms.view",
  },
  {
    id: "complaints",
    section: "5.12b",
    title: "Complaints & Feedback",
    href: "/admin/erp/complaints",
    summary: "Customer complaints, grievances, RCA, CSAT, and prevention analytics.",
    features: ["Intake", "RCA", "CSAT", "Trends", "Follow-up"],
    permission: "erp.analytics.view",
  },
  {
    id: "training",
    section: "5.2b",
    title: "Training & Development",
    href: "/admin/erp/training",
    summary: "Training calendar, content library, certifications, skills, PIP, and ROI.",
    features: ["Enrollments", "Skills", "Certs", "PIP", "ROI"],
    permission: "erp.hr.view",
  },
  {
    id: "cloud",
    section: "5.10",
    title: "AWS Cloud Infrastructure",
    href: "/staff/cloud",
    summary: "Lightsail, EC2, S3, RDS, Route53, and reseller hosting/domain inventory.",
    features: ["Resource inventory", "Cost notes", "SSL/domain sync", "Production stack"],
    permission: "erp.cloud.view",
  },
  {
    id: "monitoring",
    section: "5.11",
    title: "Server & Website Monitoring",
    href: "/staff/monitoring",
    summary: "Uptime probes, health checks, incidents, and Docker service status.",
    features: ["HTTP probes", "DB health", "Incidents", "Container status"],
    permission: "erp.monitoring.view",
  },
  {
    id: "audit",
    section: "5.17b",
    title: "Audit Logs",
    href: "/admin/erp/audit",
    summary: "Login, create, update, approve, payment, and inventory change trails.",
    features: ["Searchable", "Module filters", "Actor trail", "Export-ready"],
    permission: "erp.analytics.view",
  },
  {
    id: "staff-portal",
    section: "5.18",
    title: "Internal Staff Portal",
    href: "/staff",
    summary: "Employee dashboard, tasks, calendar, notifications, chat, and training.",
    features: ["ESS dashboard", "Notifications", "Calendar", "Training", "Chat"],
    permission: "erp.hr.view",
  },
  {
    id: "roles",
    section: "5.19",
    title: "Roles & Permissions",
    href: "/admin/erp/roles",
    summary: "CEO → Dept Head → Team Lead → Staff → Guest hierarchy with granular ACL.",
    features: ["Org roles", "Hierarchy", "Grant/revoke"],
    permission: "erp.permissions.manage",
  },
  {
    id: "dashboards",
    section: "5.20",
    title: "Executive Dashboards",
    href: "/admin/erp/dashboards",
    summary: "CEO, Finance, HR, Sales, Support, Ops, Project, and System Health.",
    features: ["CEO", "Finance", "HR", "Ops", "System health"],
    permission: "erp.analytics.view",
  },
];

export const ORG_ROLES = [
  "CEO",
  "DIRECTOR",
  "GENERAL_MANAGER",
  "DEPT_HEAD",
  "TEAM_LEAD",
  "HR",
  "FINANCE",
  "SALES",
  "MARKETING",
  "SUPPORT",
  "PROJECT_MANAGER",
  "DEVELOPER",
  "ENGINEER",
  "ACCOUNTANT",
  "AUDITOR",
  "GENERAL_STAFF",
] as const;
